### ISSUE TITLE
OAuth2 "missing access token" with gather_keys_oauth2.py

### ISSUE THREAD

**Issue by PertuyF** [orcasgit/python-fitbit#70] opened 2015-12-21 12:18 UTC
Hi,

First of all: thanks a lot for this package, it seems to work really well with oauth1.

Second: I want to use it using OAuth2 (which will be mandatory from March 2016 according to Fitbit), but I can't get my access token using your "gather_keys_oauth2.py" script.

I chose http:/127.0.0.1:8080/ as a callback url, and when I authorize access on the Fitbit page I only get this error:
(Of course client_key is the one provided for OAuth2 on my app page, and client_secret is verified to work using OAuth1)

```
ERROR: Missing access token parameter.
Please check that you are using the correct client_secret

You can close this window

  File "gather_keys_oauth2.py", line 46, in index
    self.oauth.fetch_access_token(code, self.redirect_uri)

  File "C:\Users\Fabien P\Desktop\python-fitbit-master\fitbit\api.py", line 275, in fetch_access_token
    self.token = auth.fetch_token(self.access_token_url, headers=self.auth_header, code=code)

  File "C:\Anaconda3\lib\site-packages\requests_oauthlib-0.6.0-py3.4.egg\requests_oauthlib\oauth2_session.py", line 232, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)

  File "C:\Anaconda3\lib\site-packages\oauthlib-1.0.3-py3.4.egg\oauthlib\oauth2\rfc6749\clients\base.py", line 409, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)

  File "C:\Anaconda3\lib\site-packages\oauthlib-1.0.3-py3.4.egg\oauthlib\oauth2\rfc6749\parameters.py", line 376, in parse_token_response
    validate_token_parameters(params)

  File "C:\Anaconda3\lib\site-packages\oauthlib-1.0.3-py3.4.egg\oauthlib\oauth2\rfc6749\parameters.py", line 386, in validate_token_parameters
    raise MissingTokenError(description="Missing access token parameter.")
```

I don't get what's the point of this error. This routine is done to fetch an access token from Fitbit, so how could I have one at this stage ?

But maybe I did something the wrong way, I am quite new to all this API stuff...
I though that it may be a problem with the version of my oauth2 package. If so, could you tell me what version to use ?

Any idea ?

Best,
Fabien

**Comment by PertuyF** [comment] 2015-12-21 22:03
Hi again,

As I successfully obtain my token using another Fitbit API client (https://github.com/magnific0/FitBit.py), it seems there is a problem with your script "gather_keys_oauth2.py".

I would say that oauthlib call using OAuth2Session should not try to validate the token during the request phase.

Best,
Fabien

**Comment by splunkzilla** [comment] 2015-12-22 18:46
Same issue, but without resolution for me. I have OAuth version 1 working but I need version 2 in order to do the stuff I need. Any resolution other than the one PertuyF used?

**Comment by kevingoldsmith** [comment] 2015-12-31 16:19
I'm having the same issue as well

**Comment by brad** [comment] 2016-01-01 07:25
@kevingoldsmith @splunkzilla @PertuyF This should be fixed in #72

**Comment by splunkzilla** [comment] 2016-01-01 14:36
Confirmed the fix in branch fix-oauth2. It working successfully, without any issues.

**Comment by kevingoldsmith** [comment] 2016-01-03 18:45
Also tried the branch and it works for me too.

**Comment by chw333** [comment] 2016-01-19 03:51
Also tried the branch and it works for me too.

**Comment by PertuyF** [comment] 2016-01-19 13:15
Look like it's been merged on master, it worked for me.

**Comment by bspeice** [comment] 2016-02-21 17:55
Can this fix please be released? The version available through pypi doesn't currently support OAuth2 as far as I can tell.

**Comment by randi120** [comment] 2016-03-08 01:01
I don't think this is fully working yet. 
I just ran into some trouble using the latest version (master hash 01c202397b8a79e10ede52ff172276d6a8ee26a9) which has the fixed as mentioned by @brad #70

Specifically: 
`oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.`

I revert to the version before the fix (master hash f0166f6b0f90f77e4361facdbecad925b61bbf8e)
and things work correctly. I am able to get access tokens without issues (no other changes made)

I quickly glanced at the commit diffs between the two version and this is the only change I could potentially see as being related.

**Comment by Josh2K** [comment] 2016-03-10 02:16
This also my first attempt at OAuth2.  I'm not having any luck authenticating either.  I put in  http:/127.0.0.1:8080 as my Callback URL  (is that right?) in the App registration page.  When I use the "OAuth 2.0 Client ID" and "Client (Consumer) Secret" values provided as command line parameters in gather_keys_oauth2.py, it seems to launch a webserver and causes my browser to go to a fitbit site but the webpage just says:

"Fitbit
The app you're trying to connect did not provide valid information to Fitbit. Please report this issue to them.

Developer information: invalid_request - Invalid redirect_uri parameter value"

I'm using the latest master branch.  Anyone have any suggestions?

Thanks,

**Comment by JamesGardiner** [comment] 2016-03-10 08:56
@randi120 I'm using 01c2023 without issue.

**Comment by JamesGardiner** [comment] 2016-03-10 08:58
@Josh2K your callback URL should be http://127.0.0.1:8080/, __not__ http:/127.0.0.1:8080

**Comment by randi120** [comment] 2016-03-10 15:26
@JamesGardiner  are you getting new tokens or using already saved ones? 

When I try to get tokens on 01c2023 I get the following:

```
Traceback (most recent call last):
  File "./my_oauth2_gather_key.py", line 78, in <module>
    getter.set_code(callback_answer.code)
  File "./my_oauth2_gather_key.py", line 41, in set_code
    self.oauth.fetch_access_token(code, self.redirect_url)
  File "~/fitbit/python-fitbit/fitbit/api.py", line 274, in fetch_access_token
    code=code)
  File "/usr/local/lib/python2.7/dist-packages/requests_oauthlib/oauth2_session.py", line 199, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 409, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 376, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 386, in validate_token_parameters
    raise MissingTokenError(description="Missing access token parameter.")
oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.
```
`getter` is an object that handles the generation of access token url and the passing back of the code to get new access and refresh tokens. 

It errors at the point when trading in the fitbit code for tokens. In other words, 
access token url is okay, the user has provided permission, fitbit issue the callback with the necessary code.


The same exact code works on f0166f6. 
I am not sure how to explain it...

**Comment by JamesGardiner** [comment] 2016-03-10 16:18
@randi120 I've tested both, first using an existing app and by registering a new dummy app. Both worked for me. Apologies for not being able to offer more insight to your problem.

**Comment by randi120** [comment] 2016-03-10 16:54
@JamesGardiner yeah. is a weird issue... 
thanks.

**Comment by bspeice** [comment] 2016-03-15 03:52
I've had issues in the past where I would get authorization issues if I didn't set the "redirect URL" in Fitbit to match up with what the OAuth API was using. Make sure that if you specify "localhost" as the redirect URI that you have "localhost" as the redirect URI in your fitbit application settings.

**Comment by percyperez** [comment] 2016-03-23 15:29
@randi120 I was having the same error as well but not anymore. Have you tried to install requirements in a new virtual environment? After you do that, test the package again. Also, what is the installed version of `requests-oauthlib`? Is it `0.6.1`?

**Comment by percyperez** [comment] 2016-04-01 15:28
@PertuyF If you don't have this issue anymore, can we close the issue?

**Comment by randi120** [comment] 2016-04-03 20:15
@percyperez, Thank you!
upgrading requests-oauthlib to 0.6.1 fixed the issue for me.

**Closed** 2016-04-08 15:22 UTC

**Comment by ashutosh-aneja** [comment] 2018-11-19 22:34
oauthlib.oauth2.rfc6749.errors.MissingTokenError
oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.

if 'code' not in request.args and 'state' not in request.args:
        return redirect(url_for('login'))
    else:
        google = get_google_auth(state=session['oauth_state'])
        try:
            token = google.fetch_token(Auth.TOKEN_URI,client_secret=Auth.CLIENT_SECRET,authorization_response=request.url)
        except HTTPError:
            return 'HTTPError occurred.'
        google = get_google_auth(token=token)
        resp = google.get(Auth.USER_INFO)
Open an interactive python shell in this frame        if resp.status_code == 200:



plz help me ,how to solve this
